### ISSUE TITLE
Fatal Crash

### ISSUE THREAD

**Issue by cavejay** [cavejay/one-sentence#2]
We got a fatal crash:

```

The following commands were caught:                                        
A message was sent
Someother type of message was caught
{ result: 'SUCCESS' }                                                      User x just triggered a read receipt                               -------------------------------------
we got a message from x                                              The following commands were caught:                                        
A message was sent
Someother type of message was caught                                       { result: 'SUCCESS' }
User x just triggered a read receipt
/home/pi/projects/one-sentence/app.js:116
    if (err) console.err('Ran into an error when checking if user exists'.red)
                     ^
TypeError: undefined is not a function
    at /home/pi/projects/one-sentence/app.js:116:22
    at commandHandler (/home/pi/projects/one-sentence/node_modules/mongojs/node_modules/mongodb/lib/mongodb/cursor.js:707:48)
    at null.<anonymous> (/home/pi/projects/one-sentence/node_modules/mongojs/node_modules/mongodb/lib/mongodb/db.js:1903:9)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at Base.__executeAllServerSpecificErrorCallbacks (/home/pi/projects/one-sentence/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/base.js:373:29)
    at Server.<anonymous> (/home/pi/projects/one-sentence/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:347:14)
    at Server.emit (events.js:110:17)
    at null.<anonymous> (/home/pi/projects/one-sentence/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/server.js:567:84)
    at emit (events.js:118:17)

```

**Comment by cavejay** [comment]
I haven't fixed the root cause but that will be addressed in/by another issue.
