### ISSUE TITLE
Fatal issue 

### ISSUE THREAD

**Issue by cavejay** [cavejay/one-sentence#3]
```
One-sentence/app.js:116
    if (err) console.err('Ran into an error when checking if user exists'.red)
                     ^
TypeError: undefined is not a function
    at /home/pi/projects/one-sentence/app.js:116:22                            at commandHandler (/home/pi/projects/one-sentence/node_modules/mongojs/node_modules/mongodb/lib/mongodb/cursor.js:707:48)
    at null.<anonymous> (/home/pi/projects/one-sentence/node_modules/mongojs/node_modules/mongodb/lib/mongodb/db.js:1903:9)                               at g (events.js:199:16)
    at emit (events.js:110:17)
    at Base.__executeAllServerSpecificErrorCallbacks (/home/pi/projects/one-sentence/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/base.js:373:29)
    at Server.<anonymous> (/home/pi/projects/one-sentence/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:347:14)
    at Server.emit (events.js:110:17)
    at null.<anonymous> (/home/pi/projects/one-sentence/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/server.js:567:84)
    at emit (events.js:118:17)
```

**Comment by cavejay** [comment]
This looks like it's actually the same as #2
